name: Test Windows TP Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Afficher le PATH avant l'installation de Python
      - name: Show PATH before Python installation
        run: echo $Env:PATH

      # Étape 3 : Configurer Python et installer si nécessaire
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Étape 4 : Vérifier où Python est installé sur Windows
      - name: Check if python is available
        run: |
          where python
          where python3.9

      # Étape 5 : Installer le Python avec votre script
      - name: Run installer script
        run: |
          python install.py

      # Étape 6 : Afficher le PATH après l'installation de Python
      - name: Show PATH after Python installation
        run: echo $Env:PATH

      # Étape 7 : Vérifier à nouveau si Python est dans le PATH
      - name: Check if python is available again
        run: |
          where python
          where python3.9
